sudo: required  
dist: trusty  
  
language: cpp
compiler: gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  
install:
  - sudo apt-get install -y g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 90
  - export CXX="g++-6"
  - export CC="gcc-6"
  - gcc --version && g++ --version
  - sudo apt-get install -y libgtest-dev
  - cd /usr/src/gtest
  - sudo cmake -Dgtest_disable_pthreads=ON .
  - sudo make
  - sudo mv libgtest* /usr/lib/
  - cd "${TRAVIS_BUILD_DIR}"
  
script:
  - mkdir build && cd build
  - cmake -DGTEST_ROOT=/usr/lib -DCMAKE_BUILD_TYPE="Release" ../ 
  - make
  - ./rpoint_test

