sudo: required  
dist: trusty  
  
language: cpp
compiler: gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - pip install --user pyyaml cpp-coveralls
  
install:
  - sudo apt-get install -y g++-6 
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 90
  - export CXX="g++-6"
  - export CC="gcc-6"
  - gcc --version && g++ --version
  - cd "${TRAVIS_BUILD_DIR}"
  
script:
  - mkdir build && cd build
  - cmake ../
  - make catch
  - make
  - ./rpoint_test
  - ls -la

after_success:
  - coveralls --exclude tests --exclude external --gcov-options '\-lp' 
